config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktail_ingredient_relations

  resources :cocktails
  # get "/cocktails" => cocktails#index
  # get "/cocktails/:id" => cocktails#show
  # get "/cocktails/new" => cocktails#new
  # post "/cocktails" => cocktails#create
  # get "/cocktails/:id/edit" => cocktails#edit
  # patch "/cocktails/:id" => cocktails#update
  # delete "/cocktails/:id" => cocktails#destroy

  resources :ingredients
  # get "/ingredients" => ingredients#index
  # get "/ingredients/:id" => ingredients#show
  # get "/ingredients/new" => ingredients#new
  # post "/ingredients" => ingredients#create
  # get "/ingredients/:id/edit" => ingredients#edit
  # patch "/ingredients/:id" => ingredients#update
  # delete "/ingredients/:id" => ingredients#destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :cocktail_ingredient_relations, dependent: :destroy
  has_many :ingredients, through: :cocktail_ingredient_relations, :class_name => 'Ingredient'

  has_attachments :photos, maximum: 2

  accepts_nested_attributes_for :cocktail_ingredient_relations
  accepts_nested_attributes_for :ingredients
  validates :name, presence: true

  # source: The :has_many :through relation
  # https://github.com/nathanvda/cocoon/wiki/A-guide-to-doing-nested-model-forms#the-has_many-through-relation
end

app/models/cocktail_ingredient_relation.rb
class CocktailIngredientRelation < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  # Source: https://rubyplus.com/articles/3681-Complex-Forms-in-Rails-5

  accepts_nested_attributes_for :cocktail, :reject_if => :all_blank
  accepts_nested_attributes_for :ingredient, :reject_if => :all_blank
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :cocktail_ingredient_relations, dependent: :destroy
  has_many :cocktails, through: :cocktail_ingredient_relations, :class_name => 'Cocktail'

  has_attachment :photo

  accepts_nested_attributes_for :cocktail_ingredient_relations
  accepts_nested_attributes_for :cocktails
  validates :name, presence: true

  # source: The :has_many :through relation
  # https://github.com/nathanvda/cocoon/wiki/A-guide-to-doing-nested-model-forms#the-has_many-through-relation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktail_ingredient_relations_controller.rb
class CocktailIngredientRelationsController < ApplicationController
  before_action :set_cocktail_ingredient_relation, only: [:show, :edit, :update, :destroy] 

  def index
    @cocktail_ingredient_relations = CocktailIngredientRelation.all
  end

  def show
  end

  def new
    @cocktail_ingredient_relation = CocktailIngredientRelation.new
    @cocktail_ingredient_relation.cocktail_id = params[:cocktail_id] if params[:cocktail_id]
    @cocktail_ingredient_relation.ingredient_id = params[:ingredient_id] if params[:ingredient_id]
  end

  def edit
  end

  def create
    @cocktail_ingredient_relation = CocktailIngredientRelation.new(cocktail_ingredient_relation_params)
    if @cocktail_ingredient_relation.save
      redirect_to cocktail_ingredient_relations_path
    else
      render :new
    end
  end

  def update
    if @cocktail_ingredient_relation.update(cocktail_ingredient_relation_params)
      redirect_to cocktail_ingredient_relations_path
    else
      render :edit
    end
  end

  def destroy
    @cocktail_ingredient_relation.destroy
    redirect_to cocktail_ingredient_relations_path
  end

  private

  def set_cocktail_ingredient_relation
    @cocktail_ingredient_relation = CocktailIngredientRelation.find(params[:id])
  end

  def cocktail_ingredient_relation_params
    params.require(:cocktail_ingredient_relation).permit(:cocktail_id, :ingredient_id, :description)
  end
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def edit
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktails_path
    else
      render :new
    end
  end

  def update
    if @cocktail.update(cocktail_params)
      redirect_to cocktails_path
    else
      render :edit
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, photos: [])
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  def index
    @ingredients = Ingredient.all
  end

  def show
  end

  def new
    @ingredient = Ingredient.new
  end

  def edit
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      redirect_to ingredients_path
    else
      render :new
    end
  end

  def update
    if @ingredient.update(ingredient_params)
      redirect_to ingredients_path
    else
      render :edit
    end
  end

  def destroy
    @ingredient.destroy
    redirect_to ingredients_path
  end

  private

  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end

  def ingredient_params
    params.require(:ingredient).permit(:name, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!

  def home
    @today = Date.today
    @current_time = Time.now
  end

  def team
    @members = ["Finn Pedersen"]
  end

  def join_us
    render plain: "Send us a mail"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cocktail_ingredient_relations/edit.html.erb
      <h1 class="text-center">Update Dose</h1>
      <%= simple_form_for(@cocktail_ingredient_relation) do |f| %>
        <%= f.error_notification %>
        <%= f.association :cocktail %>
        <%= f.association :ingredient %>
        <%= f.input :description, placeholder:"Description", label: "Description" %>
        <%= f.button :submit, "Update Dose", class: "btn btn-primary" %>
        <%= link_to "Cancel", :back, class: "btn btn-warning" %>
        <%= link_to "Doses", cocktail_ingredient_relations_path, class: "btn btn-primary"  %>
      <% end %>

app/views/cocktail_ingredient_relations/index.html.erb
      <h1 class="text-center">Doses</h1>
      <p>
        <%= link_to "Home Page", root_path, class: "btn btn-primary" %>
        <%= link_to "Add Dose", new_cocktail_ingredient_relation_path, class: "btn btn-primary" %>
      </p>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Cocktail</th>
            <th>Ingredient</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
          <% @cocktail_ingredient_relations.each do |cocktail_ingredient_relation| %>
            <tr>
              <td><%= link_to cocktail_ingredient_relation.cocktail.name, cocktail_ingredient_relation.cocktail %></td>
              <td><%= link_to cocktail_ingredient_relation.ingredient.name, cocktail_ingredient_relation.ingredient %></td>
              <td><%= link_to cocktail_ingredient_relation.description, cocktail_ingredient_relation_path(cocktail_ingredient_relation) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <p>
        <%= link_to "Cocktails", cocktails_path, class: "btn btn-primary"  %>
        <%= link_to "Ingredients", ingredients_path, class: "btn btn-primary"  %>
      </p>

app/views/cocktail_ingredient_relations/new.html.erb
      <h1 class="text-center">New Dose</h1>
      <%= simple_form_for(@cocktail_ingredient_relation) do |f| %>
        <%= f.error_notification %>
        <%= f.association :cocktail %>
        <%= f.association :ingredient %>
        <%= f.input :description, placeholder:"Description", label: false %>
        <%= f.button :submit, "Add Dose", class: "btn btn-primary" %>
        <%= link_to "Doses", cocktail_ingredient_relations_path, class: "btn btn-primary"  %>
      <% end %>

app/views/cocktail_ingredient_relations/show.html.erb
      <h1 class="text-center">Dose</h1>
      <p>
        <strong>Cocktail: </strong>
        <%= link_to @cocktail_ingredient_relation.cocktail.name, @cocktail_ingredient_relation.cocktail %>
      </p>
      <p>
        <strong>Ingredient: </strong>
        <%= link_to @cocktail_ingredient_relation.ingredient.name, @cocktail_ingredient_relation.ingredient %>
      </p>
      <p>
        <strong>Description: </strong>
        <%= @cocktail_ingredient_relation.description %>
      </p>
<p class="text-center">
  <%= link_to "Edit", edit_cocktail_ingredient_relation_path(@cocktail_ingredient_relation), class: "btn btn-warning " %>
  <%= link_to "Delete", cocktail_ingredient_relation_path(@cocktail_ingredient_relation), method: :delete, class: "btn btn-danger" %>
  <%= link_to "Doses", cocktail_ingredient_relations_path, class: "btn btn-primary"  %>
</p>

app/views/cocktails/edit.html.erb
      <h1 class="text-center">Update Cocktail</h1>
      <%= simple_form_for(@cocktail) do |f| %>
        <%= f.error_notification %>
        <%= f.input :name, placeholder:"Name", label: "Name" %>
        <%= f.input :photos, as: :attachinary %>
        <%= f.button :submit, "Update Cocktail", class: "btn btn-primary" %>
        <%= link_to "Cancel", :back, class: "btn btn-warning" %>
        <%= link_to "Cocktails", cocktails_path, class: "btn btn-primary"  %>
      <% end %>

app/views/cocktails/index.html.erb
      <h1 class="text-center">Cocktails</h1>
      <p>
        <%= link_to "Home Page", root_path, class: "btn btn-primary" %>
        <%= link_to "Add Cocktail", new_cocktail_path, class: "btn btn-primary" %>
      </p>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Name</th>
          </tr>
        </thead>
        <tbody>
          <% @cocktails.each do |cocktail| %>
            <tr>
              <td><%= link_to cocktail.name, cocktail_path(cocktail) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <p>
        <%= link_to "Cocktails", cocktails_path, class: "btn btn-primary"  %>
        <%= link_to "Ingredients", ingredients_path, class: "btn btn-primary"  %>
      </p>

app/views/cocktails/new.html.erb
      <h1 class="text-center">New Cocktail</h1>
      <%= simple_form_for(@cocktail) do |f| %>
        <%= f.error_notification %>
        <%= f.input :name, placeholder:"Name", label: false %>
        <%= f.input :photos, as: :attachinary %>
        <%= f.button :submit, "Add Cocktail", class: "btn btn-primary" %>
        <%= link_to "Cocktails", cocktails_path, class: "btn btn-primary"  %>
      <% end %>

app/views/cocktails/show.html.erb
      <h1 class="text-center">Cocktail</h1>
      <p>
        <p class="text-center">
          <strong>Name: </strong>
          <%= @cocktail.name %>
        </p>
        <p class="text-center">
          <% @cocktail.photos.each do |photo| %>
            <%= cl_image_tag photo.path, width: 300, height: 200, crop: :fit %>
          <% end %>
        </p>
      </p>
<p class="text-center">
  <%= link_to "Edit", edit_cocktail_path(@cocktail), class: "btn btn-warning " %>
  <%= link_to "Delete", cocktail_path(@cocktail), method: :delete, class: "btn btn-danger" %>
  <%= link_to "Cocktails", cocktails_path, class: "btn btn-primary"  %>
</p>
<h2 class="text-center">Doses</h2>
<%= link_to 'Add Dose', new_cocktail_ingredient_relation_path(cocktail_id: @cocktail.id), class: "btn btn-primary" %>
<table class="table table-bordered"'>
  <thead>
    <tr>
      <th>Ingredient</th>
      <th>Description</th>
    </tr>
  </thead>

  <tbody>
    <% @cocktail.cocktail_ingredient_relations.each do |cocktail_ingredient_relation| %>
      <tr>
        <td><%= link_to cocktail_ingredient_relation.ingredient.name, cocktail_ingredient_relation.ingredient %></td>
        <td><%= link_to cocktail_ingredient_relation.description, cocktail_ingredient_relation %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/ingredients/edit.html.erb
      <h1 class="text-center">Update Ingredient</h1>
      <%= simple_form_for(@ingredient) do |f| %>
        <%= f.error_notification %>
        <%= f.input :name, placeholder:"Name", label: "Name" %>
        <%= f.input :photo, as: :attachinary %>
        <%= f.button :submit, "Update Ingredient", class: "btn btn-primary" %>
        <%= link_to "Cancel", :back, class: "btn btn-warning" %>
        <%= link_to "Ingredients", ingredients_path, class: "btn btn-primary"  %>
      <% end %>

app/views/ingredients/index.html.erb
      <h1 class="text-center">Ingredients</h1>
      <p>
        <%= link_to "Home Page", root_path, class: "btn btn-primary" %>
        <%= link_to "Add Ingredient", new_ingredient_path, class: "btn btn-primary" %>
      </p>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Name</th>
          </tr>
        </thead>
        <tbody>
          <% @ingredients.each do |ingredient| %>
            <tr>
              <td><%= link_to ingredient.name, ingredient_path(ingredient) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <p>
        <%= link_to "Cocktails", cocktails_path, class: "btn btn-primary"  %>
        <%= link_to "Ingredients", ingredients_path, class: "btn btn-primary"  %>
      </p>

app/views/ingredients/new.html.erb
      <h1 class="text-center">New Ingredient</h1>
      <%= simple_form_for(@ingredient) do |f| %>
        <%= f.error_notification %>
        <%= f.input :name, placeholder:"Name", label: false %>
        <%= f.input :photo, as: :attachinary %>
        <%= f.button :submit, "Add Ingredient", class: "btn btn-primary" %>
        <%= link_to "Ingredients", ingredients_path, class: "btn btn-primary"  %>
      <% end %>

app/views/ingredients/show.html.erb
      <h1 class="text-center">Ingredient</h1>
      <p class="text-center">
        <strong>Name: </strong>
        <%= @ingredient.name %>
      </p>

      <p class="text-center">
        <% if @ingredient.photo? %>
          <%= cl_image_tag @ingredient.photo.path, width: 200, height: 300, crop: :fit %>
        <% end %>
      </p>
<p class="text-center">
  <%= link_to "Edit", edit_ingredient_path(@ingredient), class: "btn btn-warning " %>
  <%= link_to "Delete", ingredient_path(@ingredient), method: :delete, class: "btn btn-danger" %>
  <%= link_to "Ingredients", ingredients_path, class: "btn btn-primary"  %>
</p>
<h2 class="text-center">Doses</h2>
<%= link_to 'Add Dose', new_cocktail_ingredient_relation_path(ingredient_id: @ingredient.id), class: "btn btn-primary" %>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Cocktail</th>
      <th>Description</th>
    </tr>
  </thead>

  <tbody>
    <% @ingredient.cocktail_ingredient_relations.each do |cocktail_ingredient_relation| %>
      <tr>
        <td><%= link_to cocktail_ingredient_relation.cocktail.name, cocktail_ingredient_relation.cocktail %></td>
        <td><%= link_to cocktail_ingredient_relation.description, cocktail_ingredient_relation %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %> <!-- Append this after the main `javascript_include_tag`. -->
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome</h1>

      <p>
        <%= link_to "Cocktails", cocktails_path, class: "btn btn-primary"  %>
        <%= link_to "Ingredients", ingredients_path, class: "btn btn-primary"  %>
      </p>